USE cocktails;
INSERT INTO Recipes (Name, Garnish, Preparation) VALUES ("Yellow Bird", NULL, "Pour all ingredients into a cocktail shaker, shake well with ice, strain into chilled cocktail glass");
INSERT INTO Recipes (Name, Garnish, Preparation) VALUES ("Trinidad Sour", NULL, "Pour all ingredients into a cocktail shaker, shake well with ice, strain into chilled cocktail glass.");
INSERT INTO Recipes (Name, Garnish, Preparation) VALUES ("Tommy'S Margarita", "Lime slice", "Shake and strain into a chilled cocktail glass.");
INSERT INTO Recipes (Name, Garnish, Preparation) VALUES ("Tipperary", "Orange slice", "Pour all ingredients into mixing glass with ice cubes. Stir well. Strain into chilled cocktail glass. Garnish with a slice of orange.");
INSERT INTO Recipes (Name, Garnish, Preparation) VALUES ("Suffering Bastard", "Mint sprig, optional orange slice", "Shake everything but ginger beer with ice, pour unstrained into glass, top with ginger beer.");
INSERT INTO Recipes (Name, Garnish, Preparation) VALUES ("Aperol Spritz", "Slice of Orange", "Build all ingredients into a wine glass filled with ice. Stir gently.");
INSERT INTO Recipes (Name, Garnish, Preparation) VALUES ("Russian Spring Punch", NULL, "Pour all ingredients into cocktail shaker except the sparkling wine, shake well with ice, strain into chilled tall tumbler glass filled with ice and top up with sparkling wine.");
INSERT INTO Recipes (Name, Garnish, Preparation) VALUES ("Penicillin", "Candied ginger", "Muddle fresh ginger in a shaker and add the remaining ingredients, except for the Lagavulin whisky. Fill the shaker with ice and shake. Double-strain into a chilled old fashioned glass with ice. Float the Lagavulin whisky on top.");
INSERT INTO Recipes (Name, Garnish, Preparation) VALUES ("Paper Plane", NULL, "Pour all ingredients into cocktail shaker, shake well with ice, strain into chilled cocktail glass.");
INSERT INTO Recipes (Name, Garnish, Preparation) VALUES ("Paloma", "Slice of lime", "Pour the tequila into a highball glass, squeeze the lime juice. Add ice and salt, fill up pink grapefruit soda. Stir gently.");
INSERT INTO Recipes (Name, Garnish, Preparation) VALUES ("Old Cuban", "Mint sprigs", "Pour all ingredients except the wine into cocktail shaker, shake well with ice, strain into chilled elegant cocktail glass. Top up with the sparkling wine and garnish with mint sprigs");
INSERT INTO Recipes (Name, Garnish, Preparation) VALUES ("New York Sour", "Lemon or orange zest and cherry", "Pour the whiskey, syrup, lemon juice, and egg white into shaker with ice cubes. Shake vigorously. Strain into chilled rocks glass filled with ice. Float the wine on top. Garnish with lemon or orange zest and cherry.");
INSERT INTO Recipes (Name, Garnish, Preparation) VALUES ("Naked And Famous", NULL, "Pour all ingredients into shaker with ice cubes. Shake well. Strain into chilled cocktail glass.");
INSERT INTO Recipes (Name, Garnish, Preparation) VALUES ("Lemon Drop", "sugar around rim", "Pour all ingredients into cocktail shaker, shake well with ice, strain into chilled cocktail glass. Garnish with sugar rim around the glass.");
INSERT INTO Recipes (Name, Garnish, Preparation) VALUES ("Illegal", NULL, "Pour all ingredients into shaker with ice cubes. Shake vigorously. Strain into chilled cocktail glass, or \"on the rocks\" into a traditional clay or terracotta mug.");
INSERT INTO Recipes (Name, Garnish, Preparation) VALUES ("Fernet Con Coca", NULL, "Fill a double old-fashioned glass with ice. Pour in the Fernet-Branca, fill the glass with cola. Stir gently.");
INSERT INTO Recipes (Name, Garnish, Preparation) VALUES ("Espresso Martini", "3 coffee beans", "Pour all ingredients into cocktail shaker, shake well with ice, strain into chilled cocktail glass.");
INSERT INTO Recipes (Name, Garnish, Preparation) VALUES ("Canchanchara", "Lime wedge", "Mix honey with water and lime juice and spread the mixture on the bottom and sides of the glass. Add cracked ice, and then the rum. End by energetically stirring from bottom to top.");
INSERT INTO Recipes (Name, Garnish, Preparation) VALUES ("Bee'S Knees", "Optionally garnish with lemon or orange zest", "Stir honey syrup with lemon and orange juices until it dissolves, add gin and shake with ice. Strain into chilled cocktail glass");
INSERT INTO Recipes (Name, Garnish, Preparation) VALUES ("Barracuda", NULL, "Shake pour ingredients with ice. Strain into glass, top with sparkling wine.");
INSERT INTO Recipes (Name, Garnish, Preparation) VALUES ("Zombie", "mint sprig", "Mix ingredients in a shaker with crushed ice. Pour into a tall tumbler glass.");
INSERT INTO Recipes (Name, Garnish, Preparation) VALUES ("Vesper", "lemon zest", "Pour all ingredients into a cocktail shaker filled with ice cubes. Shake and strain into a chilled cocktail glass.");
INSERT INTO Recipes (Name, Garnish, Preparation) VALUES ("Tequila Sunrise", "orange slice and cherry", "Pour the tequila and orange juice into glass over ice.  Add the grenadine, which will sink to the bottom.  Stir gently to create the sunrise effect.  Garnish and serve.");
INSERT INTO Recipes (Name, Garnish, Preparation) VALUES ("Singapore Sling", "Maraschino cherry, pineapple", "Pour all ingredients into cocktail shaker filled with ice cubes. Shake well. Strain into highball glass. Garnish with pineapple and cocktail cherry.");
INSERT INTO Recipes (Name, Garnish, Preparation) VALUES ("Sex On The Beach", "orange slice", "Build all ingredients in a highball glass filled with ice. Garnish with orange slice.");
INSERT INTO Recipes (Name, Garnish, Preparation) VALUES ("Sea Breeze", "lime slice", "Build all ingredients in a highball glass filled with ice. Garnish with lime wedge.");
INSERT INTO Recipes (Name, Garnish, Preparation) VALUES ("Pisco Sour", "Angostura bitters (1 dash)", "Vigorously shake contents in a cocktail shaker with ice cubes, then strain into a glass and garnish with bitters.");
INSERT INTO Recipes (Name, Garnish, Preparation) VALUES ("Piña Colada", "Pineapple slice and/or maraschino cherry", "Blend all the ingredients with ice in an electric blender, pour into a large goblet or Hurricane glass and serve.");
INSERT INTO Recipes (Name, Garnish, Preparation) VALUES ("Moscow Mule", "Lime slice", "Combine vodka and ginger beer in a highball glass filled with ice. Add lime juice. Stir gently. Garnish.");
INSERT INTO Recipes (Name, Garnish, Preparation) VALUES ("Mojito", "sprigs of mint and slice of lime", "Mix mint sprigs with sugar and lime juice. Add splash of soda water and fill the glass with ice. Pour the rum and top with soda water. Light stir to involve all ingredients.");
INSERT INTO Recipes (Name, Garnish, Preparation) VALUES ("Mint Julep", "Mint sprig", "In a highball glass gently muddle the mint, sugar and water. Fill the glass with cracked ice, add Bourbon and stir well until the glass is well frosted. Garnish with a mint sprig.");
INSERT INTO Recipes (Name, Garnish, Preparation) VALUES ("Mimosa", "Orange twist", "Ensure both ingredients are well chilled, then mix into the glass. Serve cold.");
INSERT INTO Recipes (Name, Garnish, Preparation) VALUES ("Margarita", "Half salt rim (optional)", "Add all ingredients into a shaker with ice. Shake and strain into a chilled cocktail glass.");
INSERT INTO Recipes (Name, Garnish, Preparation) VALUES ("Mai Tai", "pineapple spear, mint leaves, and lime peel", "Add all ingredients into a shaker with ice. Shake and pour into a double rocks glass or a highball glass.");
INSERT INTO Recipes (Name, Garnish, Preparation) VALUES ("Long Island Iced Tea", "lemon slice (optional)", "Add all ingredients into highball glass filled with ice. Stir gently. Optionally garnish with lemon slice.");
INSERT INTO Recipes (Name, Garnish, Preparation) VALUES ("Kir", NULL, "Add the crème de cassis to the bottom of the glass, then top up with wine.");
INSERT INTO Recipes (Name, Garnish, Preparation) VALUES ("Irish Coffee", NULL, "");
INSERT INTO Recipes (Name, Garnish, Preparation) VALUES ("Horse'S Neck", "Long spiral of lemon zest", "Pour brandy and ginger ale directly into highball glass with ice cubes. Stir gently. Garnish with lemon zest. If desired, add dashes of Angostura Bitter.");
INSERT INTO Recipes (Name, Garnish, Preparation) VALUES ("Hemingway Special", NULL, "Pour all ingredients into a shaker with ice. Shake.");
INSERT INTO Recipes (Name, Garnish, Preparation) VALUES ("Grasshopper", NULL, "Pour ingredients into a cocktail shaker with ice. Shake briskly and then strain into a chilled cocktail glass.");
INSERT INTO Recipes (Name, Garnish, Preparation) VALUES ("Golden Dream", NULL, "Shake with cracked ice. Strain into glass and serve.");
INSERT INTO Recipes (Name, Garnish, Preparation) VALUES ("French Connection", NULL, "Pour all ingredients directly into old fashioned glass filled with ice cubes. Stir gently.");
INSERT INTO Recipes (Name, Garnish, Preparation) VALUES ("French 75", NULL, "Combine gin, syrup, and lemon juice in a cocktail shaker filled with ice. Shake vigorously and strain into a chilled champagne glass. Top up with champagne. Stir gently.");
INSERT INTO Recipes (Name, Garnish, Preparation) VALUES ("Rum And Coke", "Lime wedge", "Build all ingredients in a highball glass filled with ice. Garnish with lime wedge.");
INSERT INTO Recipes (Name, Garnish, Preparation) VALUES ("Cosmopolitan", "lime slice", "Shake all ingredients in cocktail shaker filled with ice. Strain into a large cocktail glass. Garnish with lime slice.");
INSERT INTO Recipes (Name, Garnish, Preparation) VALUES ("Black Russian", NULL, "Pour the ingredients into the old fashioned glass filled with ice cubes. Stir gently.");
INSERT INTO Recipes (Name, Garnish, Preparation) VALUES ("Bellini", NULL, "Pour peach purée into chilled glass, add sparkling wine. Stir gently.");
INSERT INTO Recipes (Name, Garnish, Preparation) VALUES ("White Lady", NULL, "Add all ingredients into cocktail shaker filled with ice. Shake well and strain into large cocktail glass.");
INSERT INTO Recipes (Name, Garnish, Preparation) VALUES ("Vieux Carré", "Orange zest and maraschino cherry", "Pour all ingredients into mixing glass with ice cubes. Stir well. Strain into a chilled cocktail glass.");
INSERT INTO Recipes (Name, Garnish, Preparation) VALUES ("Tuxedo", "cherry, lemon zest", "Stir all ingredients with ice and strain into a cocktail glass.  Garnish with a cherry and a twist of lemon zest.");
INSERT INTO Recipes (Name, Garnish, Preparation) VALUES ("Stinger", "Optional mint leave  [sic]", "Pour all ingredients into mixing glass with ice cubes. Stir well. Strain into chilled martini cocktail glass.");
INSERT INTO Recipes (Name, Garnish, Preparation) VALUES ("Sidecar", NULL, "Pour all ingredients into cocktail shaker filled with ice. Shake well and strain into cocktail glass.");
INSERT INTO Recipes (Name, Garnish, Preparation) VALUES ("Sazerac", "Lemon peel", "Rinse a chilled old-fashioned glass with the absinthe, add crushed ice, and set it aside. Stir the remaining ingredients over ice and set it aside. Discard the ice and any excess absinthe from the prepared glass, and strain the drink into the glass. Add the lemon peel for garnish.");
INSERT INTO Recipes (Name, Garnish, Preparation) VALUES ("Rusty Nail", "Lemon zest", "Pour all ingredients directly into an old fashioned glass filled with ice. Stir gently.");
INSERT INTO Recipes (Name, Garnish, Preparation) VALUES ("Planter'S Punch", "orange zest", "Pour all ingredients into a tumbler glass.");
INSERT INTO Recipes (Name, Garnish, Preparation) VALUES ("Old Fashioned", "Orange slice or zest, and cocktail cherry", "Place sugar cube in old fashioned glass and saturate with bitter, add few dashes of plain water. Muddle until dissolved. Fill the glass with ice cubes and add whiskey. Stir gently. Garnish with orange slice or zest, and a cocktail cherry.");
INSERT INTO Recipes (Name, Garnish, Preparation) VALUES ("Negroni", "Orange slice", "Stir into glass over ice, garnish and serve.");
INSERT INTO Recipes (Name, Garnish, Preparation) VALUES ("Monkey Gland", NULL, "Shake well over ice cubes in a shaker, strain into a chilled cocktail glass.");
INSERT INTO Recipes (Name, Garnish, Preparation) VALUES ("Mary Pickford", NULL, "Shake and strain into a chilled large cocktail glass");
INSERT INTO Recipes (Name, Garnish, Preparation) VALUES ("Martinez", "lemon zest", "Stirred over ice, strained into a chilled glass, garnished, and served up.");
INSERT INTO Recipes (Name, Garnish, Preparation) VALUES ("Manhattan", "Maraschino cherry", "Pour all ingredients into mixing glass with ice cubes. Stir well. Strain into a chilled cocktail glass.");
INSERT INTO Recipes (Name, Garnish, Preparation) VALUES ("Last Word", NULL, "Shake with ice and strain into a cocktail glass.");
INSERT INTO Recipes (Name, Garnish, Preparation) VALUES ("John Collins", "Lemon slice and maraschino cherry", "Pour all ingredients directly into highball glass filled with ice. Stir gently. Garnish. Add a dash of Angostura bitters.");
INSERT INTO Recipes (Name, Garnish, Preparation) VALUES ("Hanky-Panky Cocktail", "Orange zest", "Stirred over ice, strained into a chilled glass, garnished, and served up.");
INSERT INTO Recipes (Name, Garnish, Preparation) VALUES ("Martini", "Olive or lemon twist", "Pour all ingredients into mixing glass with ice cubes. Stir well. Strain into chilled martini cocktail glass.");
INSERT INTO Recipes (Name, Garnish, Preparation) VALUES ("Daiquiri", NULL, "In a cocktail shaker add all ingredients. Stir well to dissolve the sugar. Add ice and shake. Strain into chilled cocktail glass.");
INSERT INTO Recipes (Name, Garnish, Preparation) VALUES ("Clover Club Cocktail", NULL, "Dry shake ingredients to emulsify, add ice, shake and served straight up.");
INSERT INTO Recipes (Name, Garnish, Preparation) VALUES ("Casino", "Lemon twist and maraschino cherry", "Pour all ingredients into shaker with ice cubes. Shake well. Strain into chilled cocktail glass. Garnish with a lemon twist and a maraschino cherry. Serve without a straw.");
INSERT INTO Recipes (Name, Garnish, Preparation) VALUES ("Brandy Crusta", "Orange or Lemon Twist", "Mix all ingredients with ice cubes in a mixing glass.  Strain into slim cocktail glass rimmed with sugar.");
INSERT INTO Recipes (Name, Garnish, Preparation) VALUES ("Boulevardier", "Orange zest, optionally a lemon zest", "Pour all ingredients into mixing glass with ice cubes. Stir well. Strain into a chilled cocktail glass.");
INSERT INTO Recipes (Name, Garnish, Preparation) VALUES ("Between The Sheets", NULL, "Pour all ingredients into shaker with ice cubes, shake, strain into chilled cocktail glass.");
INSERT INTO Recipes (Name, Garnish, Preparation) VALUES ("Aviation", "cherry", "Add all ingredients into cocktail shaker filled with ice. Shake well and strain into cocktail glass. Garnish with a cherry.");
INSERT INTO Recipes (Name, Garnish, Preparation) VALUES ("Angel Face", NULL, "Pour all ingredients into cocktail shaker filled with ice cubes. Shake and strain into a chilled cocktail glass.");
INSERT INTO Recipes (Name, Garnish, Preparation) VALUES ("Americano", "half an orange slice, lemon twist", "Pour the Campari and vermouth over ice into an old fashioned glass, add a splash of soda water and garnish with half orange slice and a lemon twist.");
INSERT INTO Recipes (Name, Garnish, Preparation) VALUES ("Alexander", "nutmeg", "Pour all ingredients into cocktail shaker filled with ice cubes. Shake and strain into a chilled cocktail glass.");
INSERT INTO Ingredients (Name) VALUES ("White Rum");
INSERT INTO Ingredients (Name) VALUES ("Galliano");
INSERT INTO Ingredients (Name) VALUES ("Triple Sec");
INSERT INTO Ingredients (Name) VALUES ("Lime Juice");
INSERT INTO Ingredients (Name) VALUES ("Angostura Bitters");
INSERT INTO Ingredients (Name) VALUES ("Orgeat Syrup");
INSERT INTO Ingredients (Name) VALUES ("Lemon Juice");
INSERT INTO Ingredients (Name) VALUES ("Rye Whiskey");
INSERT INTO Ingredients (Name) VALUES ("Tequila");
INSERT INTO Ingredients (Name) VALUES ("Agave Syrup");
INSERT INTO Ingredients (Name) VALUES ("Water");
INSERT INTO Ingredients (Name) VALUES ("Irish Whiskey");
INSERT INTO Ingredients (Name) VALUES ("Red Vermouth");
INSERT INTO Ingredients (Name) VALUES ("Green Chartreuse");
INSERT INTO Ingredients (Name) VALUES ("Gin");
INSERT INTO Ingredients (Name) VALUES ("Brandy");
INSERT INTO Ingredients (Name) VALUES ("Ginger Beer");
INSERT INTO Ingredients (Name) VALUES ("Prosecco");
INSERT INTO Ingredients (Name) VALUES ("Aperol");
INSERT INTO Ingredients (Name) VALUES ("Soda Water");
INSERT INTO Ingredients (Name) VALUES ("Vodka");
INSERT INTO Ingredients (Name) VALUES ("Crème de Cassis");
INSERT INTO Ingredients (Name) VALUES ("Sugar Syrup");
INSERT INTO Ingredients (Name) VALUES ("Scotch Whisky");
INSERT INTO Ingredients (Name) VALUES ("Lagavulin 16y Whisky");
INSERT INTO Ingredients (Name) VALUES ("Honey Syrup");
INSERT INTO Ingredients (Name) VALUES ("Ginger");
INSERT INTO Ingredients (Name) VALUES ("Bourbon Whiskey");
INSERT INTO Ingredients (Name) VALUES ("Amaro Nonino");
INSERT INTO Ingredients (Name) VALUES ("100% Agave Tequila");
INSERT INTO Ingredients (Name) VALUES ("Salt");
INSERT INTO Ingredients (Name) VALUES ("Pink Grapefruit Soda");
INSERT INTO Ingredients (Name) VALUES ("Rum");
INSERT INTO Ingredients (Name) VALUES ("Simple Syrup");
INSERT INTO Ingredients (Name) VALUES ("Mint");
INSERT INTO Ingredients (Name) VALUES ("Whiskey");
INSERT INTO Ingredients (Name) VALUES ("Egg White");
INSERT INTO Ingredients (Name) VALUES ("Red Wine");
INSERT INTO Ingredients (Name) VALUES ("Mezcal");
INSERT INTO Ingredients (Name) VALUES ("Yellow Chartreuse");
INSERT INTO Ingredients (Name) VALUES ("Vodka Citron");
INSERT INTO Ingredients (Name) VALUES ("Falernum");
INSERT INTO Ingredients (Name) VALUES ("Maraschino Luxardo");
INSERT INTO Ingredients (Name) VALUES ("Fernet-Branca");
INSERT INTO Ingredients (Name) VALUES ("Cola");
INSERT INTO Ingredients (Name) VALUES ("Kahlúa");
INSERT INTO Ingredients (Name) VALUES ("Espresso");
INSERT INTO Ingredients (Name) VALUES ("Raw Honey");
INSERT INTO Ingredients (Name) VALUES ("Orange Juice");
INSERT INTO Ingredients (Name) VALUES ("Gold Rum");
INSERT INTO Ingredients (Name) VALUES ("Pineapple Juice");
INSERT INTO Ingredients (Name) VALUES ("Jamaican Dark Rum");
INSERT INTO Ingredients (Name) VALUES ("Puerto Rican Gold Rum");
INSERT INTO Ingredients (Name) VALUES ("Demerara Rum");
INSERT INTO Ingredients (Name) VALUES ("Donn's Mix");
INSERT INTO Ingredients (Name) VALUES ("Grenadine Syrup");
INSERT INTO Ingredients (Name) VALUES ("Pernod");
INSERT INTO Ingredients (Name) VALUES ("Lillet Blanc");
INSERT INTO Ingredients (Name) VALUES ("Cherry Liqueur");
INSERT INTO Ingredients (Name) VALUES ("Cointreau");
INSERT INTO Ingredients (Name) VALUES ("DOM Bénédictine");
INSERT INTO Ingredients (Name) VALUES ("Grenadine");
INSERT INTO Ingredients (Name) VALUES ("Peach Schnapps");
INSERT INTO Ingredients (Name) VALUES ("Cranberry Juice");
INSERT INTO Ingredients (Name) VALUES ("Grapefruit Juice");
INSERT INTO Ingredients (Name) VALUES ("Pisco");
INSERT INTO Ingredients (Name) VALUES ("White");
INSERT INTO Ingredients (Name) VALUES ("Aromatic Bitters");
INSERT INTO Ingredients (Name) VALUES ("Coconut Cream");
INSERT INTO Ingredients (Name) VALUES ("White Cane Sugar");
INSERT INTO Ingredients (Name) VALUES ("Leaves");
INSERT INTO Ingredients (Name) VALUES ("Powdered Sugar");
INSERT INTO Ingredients (Name) VALUES ("Champagne");
INSERT INTO Ingredients (Name) VALUES ("Tequila 100% Agave");
INSERT INTO Ingredients (Name) VALUES ("Amber Jamaican Rum");
INSERT INTO Ingredients (Name) VALUES ("Martinique Molasses Rum");
INSERT INTO Ingredients (Name) VALUES ("Orange Curaçao");
INSERT INTO Ingredients (Name) VALUES ("White Wine");
INSERT INTO Ingredients (Name) VALUES ("Hot Coffee");
INSERT INTO Ingredients (Name) VALUES ("Cream");
INSERT INTO Ingredients (Name) VALUES ("Brown Sugar");
INSERT INTO Ingredients (Name) VALUES ("Ginger Ale");
INSERT INTO Ingredients (Name) VALUES ("Angostura bitter");
INSERT INTO Ingredients (Name) VALUES ("Maraschino Liqueur");
INSERT INTO Ingredients (Name) VALUES ("Crème de Menthe");
INSERT INTO Ingredients (Name) VALUES ("Crème de Cacao");
INSERT INTO Ingredients (Name) VALUES ("Cognac");
INSERT INTO Ingredients (Name) VALUES ("Amaretto liqueur");
INSERT INTO Ingredients (Name) VALUES ("Coffee Liqueur");
INSERT INTO Ingredients (Name) VALUES ("Fresh Peach Purée");
INSERT INTO Ingredients (Name) VALUES ("Sweet Vermouth");
INSERT INTO Ingredients (Name) VALUES ("Spoon Bénédictine");
INSERT INTO Ingredients (Name) VALUES ("Peychaud's Bitters");
INSERT INTO Ingredients (Name) VALUES ("Dry Vermouth");
INSERT INTO Ingredients (Name) VALUES ("Maraschino");
INSERT INTO Ingredients (Name) VALUES ("Absinthe");
INSERT INTO Ingredients (Name) VALUES ("Orange Bitters");
INSERT INTO Ingredients (Name) VALUES ("White Crème de Menthe");
INSERT INTO Ingredients (Name) VALUES ("Sugar");
INSERT INTO Ingredients (Name) VALUES ("Drambuie");
INSERT INTO Ingredients (Name) VALUES ("Jamaican Rum");
INSERT INTO Ingredients (Name) VALUES ("Sugar Cane Juice");
INSERT INTO Ingredients (Name) VALUES ("Bourbon Or Rye Whiskey");
INSERT INTO Ingredients (Name) VALUES ("Cube");
INSERT INTO Ingredients (Name) VALUES ("Sweet Red Vermouth");
INSERT INTO Ingredients (Name) VALUES ("Campari");
INSERT INTO Ingredients (Name) VALUES ("London Dry Gin");
INSERT INTO Ingredients (Name) VALUES ("Spoon Maraschino Liqueur");
INSERT INTO Ingredients (Name) VALUES ("Carbonated Water");
INSERT INTO Ingredients (Name) VALUES ("Fernet Branca");
INSERT INTO Ingredients (Name) VALUES ("Raspberry Syrup");
INSERT INTO Ingredients (Name) VALUES ("Spoon Curaçao");
INSERT INTO Ingredients (Name) VALUES ("Bitter Campari");
INSERT INTO Ingredients (Name) VALUES ("Crème de Violette");
INSERT INTO Ingredients (Name) VALUES ("Apricot Brandy");
INSERT INTO Ingredients (Name) VALUES ("Calvados");
INSERT INTO Dosages (RecipeId, IngredientId, Amount, Unit) VALUES (1, 1, 3, "cl");
INSERT INTO Dosages (RecipeId, IngredientId, Amount, Unit) VALUES (1, 2, 1.5, "cl");
INSERT INTO Dosages (RecipeId, IngredientId, Amount, Unit) VALUES (1, 3, 1.5, "cl");
INSERT INTO Dosages (RecipeId, IngredientId, Amount, Unit) VALUES (1, 4, 1.5, "cl");
INSERT INTO Dosages (RecipeId, IngredientId, Amount, Unit) VALUES (2, 5, 4.5, "cl");
INSERT INTO Dosages (RecipeId, IngredientId, Amount, Unit) VALUES (2, 6, 3, "cl");
INSERT INTO Dosages (RecipeId, IngredientId, Amount, Unit) VALUES (2, 7, 2.25, "cl");
INSERT INTO Dosages (RecipeId, IngredientId, Amount, Unit) VALUES (2, 8, 1.5, "cl");
INSERT INTO Dosages (RecipeId, IngredientId, Amount, Unit) VALUES (3, 9, 6, "cl");
INSERT INTO Dosages (RecipeId, IngredientId, Amount, Unit) VALUES (3, 4, 3, "cl");
INSERT INTO Dosages (RecipeId, IngredientId, Amount, Unit) VALUES (3, 10, 1.5, "cl");
INSERT INTO Dosages (RecipeId, IngredientId, Amount, Unit) VALUES (3, 11, 1.5, "cl");
INSERT INTO Dosages (RecipeId, IngredientId, Amount, Unit) VALUES (4, 12, 5, "cl");
INSERT INTO Dosages (RecipeId, IngredientId, Amount, Unit) VALUES (4, 13, 2.5, "cl");
INSERT INTO Dosages (RecipeId, IngredientId, Amount, Unit) VALUES (4, 14, 1.5, "cl");
INSERT INTO Dosages (RecipeId, IngredientId, Amount, Unit) VALUES (4, 5, 2, "dashes");
INSERT INTO Dosages (RecipeId, IngredientId, Amount, Unit) VALUES (5, 15, 30, "ml");
INSERT INTO Dosages (RecipeId, IngredientId, Amount, Unit) VALUES (5, 16, 30, "ml");
INSERT INTO Dosages (RecipeId, IngredientId, Amount, Unit) VALUES (5, 4, 15, "ml");
INSERT INTO Dosages (RecipeId, IngredientId, Amount, Unit) VALUES (5, 5, 2, "dashes");
INSERT INTO Dosages (RecipeId, IngredientId, Amount, Unit) VALUES (5, 17, 0, "top up");
INSERT INTO Dosages (RecipeId, IngredientId, Amount, Unit) VALUES (6, 18, 9, "cl");
INSERT INTO Dosages (RecipeId, IngredientId, Amount, Unit) VALUES (6, 19, 6, "cl");
INSERT INTO Dosages (RecipeId, IngredientId, Amount, Unit) VALUES (6, 20, 0, "Splash");
INSERT INTO Dosages (RecipeId, IngredientId, Amount, Unit) VALUES (7, 21, 2.5, "cl");
INSERT INTO Dosages (RecipeId, IngredientId, Amount, Unit) VALUES (7, 22, 1.5, "cl");
INSERT INTO Dosages (RecipeId, IngredientId, Amount, Unit) VALUES (7, 23, 1, "cl");
INSERT INTO Dosages (RecipeId, IngredientId, Amount, Unit) VALUES (7, 7, 2.5, "cl");
INSERT INTO Dosages (RecipeId, IngredientId, Amount, Unit) VALUES (8, 24, 6, "cl");
INSERT INTO Dosages (RecipeId, IngredientId, Amount, Unit) VALUES (8, 25, 0.75, "cl");
INSERT INTO Dosages (RecipeId, IngredientId, Amount, Unit) VALUES (8, 7, 2.25, "cl");
INSERT INTO Dosages (RecipeId, IngredientId, Amount, Unit) VALUES (8, 26, 2.25, "cl");
INSERT INTO Dosages (RecipeId, IngredientId, Amount, Unit) VALUES (8, 27, 2, "slices");
INSERT INTO Dosages (RecipeId, IngredientId, Amount, Unit) VALUES (9, 28, 3, "cl");
INSERT INTO Dosages (RecipeId, IngredientId, Amount, Unit) VALUES (9, 29, 3, "cl");
INSERT INTO Dosages (RecipeId, IngredientId, Amount, Unit) VALUES (9, 19, 3, "cl");
INSERT INTO Dosages (RecipeId, IngredientId, Amount, Unit) VALUES (9, 7, 3, "cl");
INSERT INTO Dosages (RecipeId, IngredientId, Amount, Unit) VALUES (10, 30, 50, "ml");
INSERT INTO Dosages (RecipeId, IngredientId, Amount, Unit) VALUES (10, 4, 5, "ml");
INSERT INTO Dosages (RecipeId, IngredientId, Amount, Unit) VALUES (10, 31, 1, "pinch");
INSERT INTO Dosages (RecipeId, IngredientId, Amount, Unit) VALUES (10, 32, 100, "ml");
INSERT INTO Dosages (RecipeId, IngredientId, Amount, Unit) VALUES (11, 33, 4.5, "cl");
INSERT INTO Dosages (RecipeId, IngredientId, Amount, Unit) VALUES (11, 4, 2.25, "cl");
INSERT INTO Dosages (RecipeId, IngredientId, Amount, Unit) VALUES (11, 34, 3, "cl");
INSERT INTO Dosages (RecipeId, IngredientId, Amount, Unit) VALUES (11, 5, 2, "dashes");
INSERT INTO Dosages (RecipeId, IngredientId, Amount, Unit) VALUES (11, 35, 6, "leaves");
INSERT INTO Dosages (RecipeId, IngredientId, Amount, Unit) VALUES (11, 18, 6, "cl");
INSERT INTO Dosages (RecipeId, IngredientId, Amount, Unit) VALUES (12, 36, 6, "cl");
INSERT INTO Dosages (RecipeId, IngredientId, Amount, Unit) VALUES (12, 34, 2.25, "cl");
INSERT INTO Dosages (RecipeId, IngredientId, Amount, Unit) VALUES (12, 7, 3, "cl");
INSERT INTO Dosages (RecipeId, IngredientId, Amount, Unit) VALUES (12, 37, 2, "drops");
INSERT INTO Dosages (RecipeId, IngredientId, Amount, Unit) VALUES (12, 38, 1.5, "cl");
INSERT INTO Dosages (RecipeId, IngredientId, Amount, Unit) VALUES (13, 39, 2.25, "cl");
INSERT INTO Dosages (RecipeId, IngredientId, Amount, Unit) VALUES (13, 40, 2.25, "cl");
INSERT INTO Dosages (RecipeId, IngredientId, Amount, Unit) VALUES (13, 19, 2.25, "cl");
INSERT INTO Dosages (RecipeId, IngredientId, Amount, Unit) VALUES (13, 4, 2.25, "cl");
INSERT INTO Dosages (RecipeId, IngredientId, Amount, Unit) VALUES (14, 41, 30, "ml");
INSERT INTO Dosages (RecipeId, IngredientId, Amount, Unit) VALUES (14, 3, 20, "ml");
INSERT INTO Dosages (RecipeId, IngredientId, Amount, Unit) VALUES (14, 7, 15, "ml");
INSERT INTO Dosages (RecipeId, IngredientId, Amount, Unit) VALUES (15, 39, 3, "cl");
INSERT INTO Dosages (RecipeId, IngredientId, Amount, Unit) VALUES (15, 1, 1.5, "cl");
INSERT INTO Dosages (RecipeId, IngredientId, Amount, Unit) VALUES (15, 42, 1.5, "cl");
INSERT INTO Dosages (RecipeId, IngredientId, Amount, Unit) VALUES (15, 43, 1, "barspoon");
INSERT INTO Dosages (RecipeId, IngredientId, Amount, Unit) VALUES (15, 4, 2.25, "cl");
INSERT INTO Dosages (RecipeId, IngredientId, Amount, Unit) VALUES (15, 34, 1.5, "cl");
INSERT INTO Dosages (RecipeId, IngredientId, Amount, Unit) VALUES (15, 37, 2, "drops");
INSERT INTO Dosages (RecipeId, IngredientId, Amount, Unit) VALUES (16, 44, 5, "cl");
INSERT INTO Dosages (RecipeId, IngredientId, Amount, Unit) VALUES (16, 45, 0, "top up");
INSERT INTO Dosages (RecipeId, IngredientId, Amount, Unit) VALUES (17, 21, 50, "ml");
INSERT INTO Dosages (RecipeId, IngredientId, Amount, Unit) VALUES (17, 46, 30, "ml");
INSERT INTO Dosages (RecipeId, IngredientId, Amount, Unit) VALUES (17, 23, 10, "ml");
INSERT INTO Dosages (RecipeId, IngredientId, Amount, Unit) VALUES (17, 47, 1, "strong");
INSERT INTO Dosages (RecipeId, IngredientId, Amount, Unit) VALUES (18, 33, 6, "cl");
INSERT INTO Dosages (RecipeId, IngredientId, Amount, Unit) VALUES (18, 4, 1.5, "cl");
INSERT INTO Dosages (RecipeId, IngredientId, Amount, Unit) VALUES (18, 48, 1.5, "cl");
INSERT INTO Dosages (RecipeId, IngredientId, Amount, Unit) VALUES (18, 11, 5, "cl");
INSERT INTO Dosages (RecipeId, IngredientId, Amount, Unit) VALUES (19, 15, 52.5, "ml");
INSERT INTO Dosages (RecipeId, IngredientId, Amount, Unit) VALUES (19, 7, 22.5, "ml");
INSERT INTO Dosages (RecipeId, IngredientId, Amount, Unit) VALUES (19, 49, 22.5, "ml");
INSERT INTO Dosages (RecipeId, IngredientId, Amount, Unit) VALUES (19, 26, 2, "teaspoons");
INSERT INTO Dosages (RecipeId, IngredientId, Amount, Unit) VALUES (20, 50, 4.5, "cl");
INSERT INTO Dosages (RecipeId, IngredientId, Amount, Unit) VALUES (20, 2, 1.5, "cl");
INSERT INTO Dosages (RecipeId, IngredientId, Amount, Unit) VALUES (20, 51, 6, "cl");
INSERT INTO Dosages (RecipeId, IngredientId, Amount, Unit) VALUES (20, 4, 1, "dash");
INSERT INTO Dosages (RecipeId, IngredientId, Amount, Unit) VALUES (20, 18, 0, "top up");
INSERT INTO Dosages (RecipeId, IngredientId, Amount, Unit) VALUES (21, 52, 45, "ml");
INSERT INTO Dosages (RecipeId, IngredientId, Amount, Unit) VALUES (21, 53, 45, "ml");
INSERT INTO Dosages (RecipeId, IngredientId, Amount, Unit) VALUES (21, 54, 30, "ml");
INSERT INTO Dosages (RecipeId, IngredientId, Amount, Unit) VALUES (21, 4, 20, "ml");
INSERT INTO Dosages (RecipeId, IngredientId, Amount, Unit) VALUES (21, 42, 15, "ml");
INSERT INTO Dosages (RecipeId, IngredientId, Amount, Unit) VALUES (21, 55, 15, "ml");
INSERT INTO Dosages (RecipeId, IngredientId, Amount, Unit) VALUES (21, 56, 1, "tsp");
INSERT INTO Dosages (RecipeId, IngredientId, Amount, Unit) VALUES (21, 5, 1, "dash");
INSERT INTO Dosages (RecipeId, IngredientId, Amount, Unit) VALUES (21, 57, 6, "drops");
INSERT INTO Dosages (RecipeId, IngredientId, Amount, Unit) VALUES (22, 15, 45, "ml");
INSERT INTO Dosages (RecipeId, IngredientId, Amount, Unit) VALUES (22, 21, 15, "ml");
INSERT INTO Dosages (RecipeId, IngredientId, Amount, Unit) VALUES (22, 58, 7.5, "ml");
INSERT INTO Dosages (RecipeId, IngredientId, Amount, Unit) VALUES (23, 9, 4.5, "cl");
INSERT INTO Dosages (RecipeId, IngredientId, Amount, Unit) VALUES (23, 49, 9, "cl");
INSERT INTO Dosages (RecipeId, IngredientId, Amount, Unit) VALUES (23, 56, 1.5, "cl");
INSERT INTO Dosages (RecipeId, IngredientId, Amount, Unit) VALUES (24, 15, 3, "cl");
INSERT INTO Dosages (RecipeId, IngredientId, Amount, Unit) VALUES (24, 59, 1.5, "cl");
INSERT INTO Dosages (RecipeId, IngredientId, Amount, Unit) VALUES (24, 60, 0.75, "cl");
INSERT INTO Dosages (RecipeId, IngredientId, Amount, Unit) VALUES (24, 61, 0.75, "cl");
INSERT INTO Dosages (RecipeId, IngredientId, Amount, Unit) VALUES (24, 62, 1, "cl");
INSERT INTO Dosages (RecipeId, IngredientId, Amount, Unit) VALUES (24, 51, 12, "cl");
INSERT INTO Dosages (RecipeId, IngredientId, Amount, Unit) VALUES (24, 4, 1.5, "cl");
INSERT INTO Dosages (RecipeId, IngredientId, Amount, Unit) VALUES (24, 5, 1, "dash");
INSERT INTO Dosages (RecipeId, IngredientId, Amount, Unit) VALUES (25, 21, 4, "cl");
INSERT INTO Dosages (RecipeId, IngredientId, Amount, Unit) VALUES (25, 63, 2, "cl");
INSERT INTO Dosages (RecipeId, IngredientId, Amount, Unit) VALUES (25, 49, 4, "cl");
INSERT INTO Dosages (RecipeId, IngredientId, Amount, Unit) VALUES (25, 64, 4, "cl");
INSERT INTO Dosages (RecipeId, IngredientId, Amount, Unit) VALUES (26, 21, 4, "cl");
INSERT INTO Dosages (RecipeId, IngredientId, Amount, Unit) VALUES (26, 64, 12, "cl");
INSERT INTO Dosages (RecipeId, IngredientId, Amount, Unit) VALUES (26, 65, 3, "cl");
INSERT INTO Dosages (RecipeId, IngredientId, Amount, Unit) VALUES (27, 66, 60, "ml");
INSERT INTO Dosages (RecipeId, IngredientId, Amount, Unit) VALUES (27, 7, 30, "ml");
INSERT INTO Dosages (RecipeId, IngredientId, Amount, Unit) VALUES (27, 34, 20, "ml");
INSERT INTO Dosages (RecipeId, IngredientId, Amount, Unit) VALUES (27, 67, 1, "egg");
INSERT INTO Dosages (RecipeId, IngredientId, Amount, Unit) VALUES (27, 68, 3, "drops ");
INSERT INTO Dosages (RecipeId, IngredientId, Amount, Unit) VALUES (28, 1, 5, "parts");
INSERT INTO Dosages (RecipeId, IngredientId, Amount, Unit) VALUES (28, 69, 3, "parts");
INSERT INTO Dosages (RecipeId, IngredientId, Amount, Unit) VALUES (28, 51, 5, "parts");
INSERT INTO Dosages (RecipeId, IngredientId, Amount, Unit) VALUES (29, 21, 4.5, "cl");
INSERT INTO Dosages (RecipeId, IngredientId, Amount, Unit) VALUES (29, 4, 1, "cl");
INSERT INTO Dosages (RecipeId, IngredientId, Amount, Unit) VALUES (29, 17, 12, "cl");
INSERT INTO Dosages (RecipeId, IngredientId, Amount, Unit) VALUES (30, 1, 45, "ml");
INSERT INTO Dosages (RecipeId, IngredientId, Amount, Unit) VALUES (30, 4, 20, "ml");
INSERT INTO Dosages (RecipeId, IngredientId, Amount, Unit) VALUES (30, 35, 6, "sprigs");
INSERT INTO Dosages (RecipeId, IngredientId, Amount, Unit) VALUES (30, 70, 2, "teaspoons");
INSERT INTO Dosages (RecipeId, IngredientId, Amount, Unit) VALUES (30, 20, 0, "top up");
INSERT INTO Dosages (RecipeId, IngredientId, Amount, Unit) VALUES (31, 28, 6, "cL");
INSERT INTO Dosages (RecipeId, IngredientId, Amount, Unit) VALUES (31, 71, 4, "mint");
INSERT INTO Dosages (RecipeId, IngredientId, Amount, Unit) VALUES (31, 72, 1, "teaspoon");
INSERT INTO Dosages (RecipeId, IngredientId, Amount, Unit) VALUES (31, 11, 2, "teaspoons");
INSERT INTO Dosages (RecipeId, IngredientId, Amount, Unit) VALUES (32, 73, 7.5, "cl");
INSERT INTO Dosages (RecipeId, IngredientId, Amount, Unit) VALUES (32, 49, 7.5, "cl");
INSERT INTO Dosages (RecipeId, IngredientId, Amount, Unit) VALUES (33, 74, 50, "ml");
INSERT INTO Dosages (RecipeId, IngredientId, Amount, Unit) VALUES (33, 3, 20, "ml");
INSERT INTO Dosages (RecipeId, IngredientId, Amount, Unit) VALUES (33, 4, 15, "ml");
INSERT INTO Dosages (RecipeId, IngredientId, Amount, Unit) VALUES (34, 75, 30, "ml");
INSERT INTO Dosages (RecipeId, IngredientId, Amount, Unit) VALUES (34, 76, 30, "ml");
INSERT INTO Dosages (RecipeId, IngredientId, Amount, Unit) VALUES (34, 77, 15, "ml");
INSERT INTO Dosages (RecipeId, IngredientId, Amount, Unit) VALUES (34, 6, 15, "ml");
INSERT INTO Dosages (RecipeId, IngredientId, Amount, Unit) VALUES (34, 4, 30, "ml");
INSERT INTO Dosages (RecipeId, IngredientId, Amount, Unit) VALUES (34, 34, 7.5, "ml");
INSERT INTO Dosages (RecipeId, IngredientId, Amount, Unit) VALUES (35, 9, 15, "ml");
INSERT INTO Dosages (RecipeId, IngredientId, Amount, Unit) VALUES (35, 21, 15, "ml");
INSERT INTO Dosages (RecipeId, IngredientId, Amount, Unit) VALUES (35, 1, 15, "ml");
INSERT INTO Dosages (RecipeId, IngredientId, Amount, Unit) VALUES (35, 60, 15, "ml");
INSERT INTO Dosages (RecipeId, IngredientId, Amount, Unit) VALUES (35, 15, 15, "ml");
INSERT INTO Dosages (RecipeId, IngredientId, Amount, Unit) VALUES (35, 7, 30, "ml");
INSERT INTO Dosages (RecipeId, IngredientId, Amount, Unit) VALUES (35, 34, 20, "ml");
INSERT INTO Dosages (RecipeId, IngredientId, Amount, Unit) VALUES (35, 45, 0, "top up");
INSERT INTO Dosages (RecipeId, IngredientId, Amount, Unit) VALUES (36, 78, 9, "cl");
INSERT INTO Dosages (RecipeId, IngredientId, Amount, Unit) VALUES (36, 22, 1, "cl");
INSERT INTO Dosages (RecipeId, IngredientId, Amount, Unit) VALUES (37, 12, 4, "cl");
INSERT INTO Dosages (RecipeId, IngredientId, Amount, Unit) VALUES (37, 79, 8, "cl");
INSERT INTO Dosages (RecipeId, IngredientId, Amount, Unit) VALUES (37, 80, 3, "cl");
INSERT INTO Dosages (RecipeId, IngredientId, Amount, Unit) VALUES (37, 81, 1, "tsp");
INSERT INTO Dosages (RecipeId, IngredientId, Amount, Unit) VALUES (38, 16, 4, "cl");
INSERT INTO Dosages (RecipeId, IngredientId, Amount, Unit) VALUES (38, 82, 12, "cl");
INSERT INTO Dosages (RecipeId, IngredientId, Amount, Unit) VALUES (38, 83, 1, "dash");
INSERT INTO Dosages (RecipeId, IngredientId, Amount, Unit) VALUES (39, 33, 6, "cl");
INSERT INTO Dosages (RecipeId, IngredientId, Amount, Unit) VALUES (39, 65, 4, "cl");
INSERT INTO Dosages (RecipeId, IngredientId, Amount, Unit) VALUES (39, 84, 1.5, "cL");
INSERT INTO Dosages (RecipeId, IngredientId, Amount, Unit) VALUES (39, 4, 1.5, "cl");
INSERT INTO Dosages (RecipeId, IngredientId, Amount, Unit) VALUES (40, 85, 3, "cl");
INSERT INTO Dosages (RecipeId, IngredientId, Amount, Unit) VALUES (40, 86, 3, "cl");
INSERT INTO Dosages (RecipeId, IngredientId, Amount, Unit) VALUES (40, 80, 3, "cl");
INSERT INTO Dosages (RecipeId, IngredientId, Amount, Unit) VALUES (41, 2, 2, "cl");
INSERT INTO Dosages (RecipeId, IngredientId, Amount, Unit) VALUES (41, 3, 2, "cl");
INSERT INTO Dosages (RecipeId, IngredientId, Amount, Unit) VALUES (41, 49, 2, "cl");
INSERT INTO Dosages (RecipeId, IngredientId, Amount, Unit) VALUES (41, 80, 1, "cl");
INSERT INTO Dosages (RecipeId, IngredientId, Amount, Unit) VALUES (42, 87, 3.5, "cl");
INSERT INTO Dosages (RecipeId, IngredientId, Amount, Unit) VALUES (42, 88, 3.5, "cl");
INSERT INTO Dosages (RecipeId, IngredientId, Amount, Unit) VALUES (43, 15, 30, "ml");
INSERT INTO Dosages (RecipeId, IngredientId, Amount, Unit) VALUES (43, 7, 15, "ml");
INSERT INTO Dosages (RecipeId, IngredientId, Amount, Unit) VALUES (43, 34, 15, "ml");
INSERT INTO Dosages (RecipeId, IngredientId, Amount, Unit) VALUES (43, 73, 60, "ml");
INSERT INTO Dosages (RecipeId, IngredientId, Amount, Unit) VALUES (44, 45, 120, "ml");
INSERT INTO Dosages (RecipeId, IngredientId, Amount, Unit) VALUES (44, 1, 50, "ml");
INSERT INTO Dosages (RecipeId, IngredientId, Amount, Unit) VALUES (44, 4, 10, "ml");
INSERT INTO Dosages (RecipeId, IngredientId, Amount, Unit) VALUES (45, 41, 4, "cl");
INSERT INTO Dosages (RecipeId, IngredientId, Amount, Unit) VALUES (45, 60, 1.5, "cl");
INSERT INTO Dosages (RecipeId, IngredientId, Amount, Unit) VALUES (45, 4, 1.5, "cl");
INSERT INTO Dosages (RecipeId, IngredientId, Amount, Unit) VALUES (45, 64, 3, "cl");
INSERT INTO Dosages (RecipeId, IngredientId, Amount, Unit) VALUES (46, 21, 50, "ml");
INSERT INTO Dosages (RecipeId, IngredientId, Amount, Unit) VALUES (46, 89, 20, "ml");
INSERT INTO Dosages (RecipeId, IngredientId, Amount, Unit) VALUES (47, 18, 10, "cl");
INSERT INTO Dosages (RecipeId, IngredientId, Amount, Unit) VALUES (47, 90, 5, "cl");
INSERT INTO Dosages (RecipeId, IngredientId, Amount, Unit) VALUES (48, 15, 4, "cl");
INSERT INTO Dosages (RecipeId, IngredientId, Amount, Unit) VALUES (48, 3, 3, "cl");
INSERT INTO Dosages (RecipeId, IngredientId, Amount, Unit) VALUES (48, 7, 2, "cl");
INSERT INTO Dosages (RecipeId, IngredientId, Amount, Unit) VALUES (49, 8, 30, "ml");
INSERT INTO Dosages (RecipeId, IngredientId, Amount, Unit) VALUES (49, 87, 30, "ml");
INSERT INTO Dosages (RecipeId, IngredientId, Amount, Unit) VALUES (49, 91, 30, "ml");
INSERT INTO Dosages (RecipeId, IngredientId, Amount, Unit) VALUES (49, 92, 1, "bar");
INSERT INTO Dosages (RecipeId, IngredientId, Amount, Unit) VALUES (49, 93, 2, "dashes");
INSERT INTO Dosages (RecipeId, IngredientId, Amount, Unit) VALUES (50, 15, 3, "cl");
INSERT INTO Dosages (RecipeId, IngredientId, Amount, Unit) VALUES (50, 94, 3, "cl");
INSERT INTO Dosages (RecipeId, IngredientId, Amount, Unit) VALUES (50, 95, 0.5, "barspoon");
INSERT INTO Dosages (RecipeId, IngredientId, Amount, Unit) VALUES (50, 96, 0.25, "barspoon");
INSERT INTO Dosages (RecipeId, IngredientId, Amount, Unit) VALUES (50, 97, 3, "dashes");
INSERT INTO Dosages (RecipeId, IngredientId, Amount, Unit) VALUES (51, 87, 50, "ml");
INSERT INTO Dosages (RecipeId, IngredientId, Amount, Unit) VALUES (51, 98, 20, "ml");
INSERT INTO Dosages (RecipeId, IngredientId, Amount, Unit) VALUES (52, 87, 5, "cl");
INSERT INTO Dosages (RecipeId, IngredientId, Amount, Unit) VALUES (52, 3, 2, "cl");
INSERT INTO Dosages (RecipeId, IngredientId, Amount, Unit) VALUES (52, 7, 2, "cl");
INSERT INTO Dosages (RecipeId, IngredientId, Amount, Unit) VALUES (53, 87, 5, "cl");
INSERT INTO Dosages (RecipeId, IngredientId, Amount, Unit) VALUES (53, 96, 1, "cl");
INSERT INTO Dosages (RecipeId, IngredientId, Amount, Unit) VALUES (53, 99, 1, "cube");
INSERT INTO Dosages (RecipeId, IngredientId, Amount, Unit) VALUES (53, 93, 2, "dashes");
INSERT INTO Dosages (RecipeId, IngredientId, Amount, Unit) VALUES (54, 24, 45, "ml");
INSERT INTO Dosages (RecipeId, IngredientId, Amount, Unit) VALUES (54, 100, 25, "ml");
INSERT INTO Dosages (RecipeId, IngredientId, Amount, Unit) VALUES (55, 101, 4.5, "cl");
INSERT INTO Dosages (RecipeId, IngredientId, Amount, Unit) VALUES (55, 4, 1.5, "cl");
INSERT INTO Dosages (RecipeId, IngredientId, Amount, Unit) VALUES (55, 102, 3, "cl");
INSERT INTO Dosages (RecipeId, IngredientId, Amount, Unit) VALUES (56, 103, 45, "ml");
INSERT INTO Dosages (RecipeId, IngredientId, Amount, Unit) VALUES (56, 104, 1, "sugar");
INSERT INTO Dosages (RecipeId, IngredientId, Amount, Unit) VALUES (56, 5, 2, "dashes");
INSERT INTO Dosages (RecipeId, IngredientId, Amount, Unit) VALUES (56, 11, 2, "dashes");
INSERT INTO Dosages (RecipeId, IngredientId, Amount, Unit) VALUES (57, 15, 3, "cl");
INSERT INTO Dosages (RecipeId, IngredientId, Amount, Unit) VALUES (57, 105, 3, "cl");
INSERT INTO Dosages (RecipeId, IngredientId, Amount, Unit) VALUES (57, 106, 3, "cl");
INSERT INTO Dosages (RecipeId, IngredientId, Amount, Unit) VALUES (58, 15, 45, "ml");
INSERT INTO Dosages (RecipeId, IngredientId, Amount, Unit) VALUES (58, 49, 45, "ml");
INSERT INTO Dosages (RecipeId, IngredientId, Amount, Unit) VALUES (58, 96, 1, "tablespoon");
INSERT INTO Dosages (RecipeId, IngredientId, Amount, Unit) VALUES (58, 62, 1, "tablespoon");
INSERT INTO Dosages (RecipeId, IngredientId, Amount, Unit) VALUES (59, 1, 4.5, "cl");
INSERT INTO Dosages (RecipeId, IngredientId, Amount, Unit) VALUES (59, 51, 4.5, "cl");
INSERT INTO Dosages (RecipeId, IngredientId, Amount, Unit) VALUES (59, 62, 0.5, "cl");
INSERT INTO Dosages (RecipeId, IngredientId, Amount, Unit) VALUES (59, 95, 0.75, "cl");
INSERT INTO Dosages (RecipeId, IngredientId, Amount, Unit) VALUES (60, 107, 45, "ml");
INSERT INTO Dosages (RecipeId, IngredientId, Amount, Unit) VALUES (60, 105, 45, "ml");
INSERT INTO Dosages (RecipeId, IngredientId, Amount, Unit) VALUES (60, 108, 1, "Bar");
INSERT INTO Dosages (RecipeId, IngredientId, Amount, Unit) VALUES (60, 97, 2, "Dashes");
INSERT INTO Dosages (RecipeId, IngredientId, Amount, Unit) VALUES (61, 8, 50, "ml");
INSERT INTO Dosages (RecipeId, IngredientId, Amount, Unit) VALUES (61, 105, 20, "ml");
INSERT INTO Dosages (RecipeId, IngredientId, Amount, Unit) VALUES (61, 5, 1, "dash");
INSERT INTO Dosages (RecipeId, IngredientId, Amount, Unit) VALUES (62, 15, 22.5, "ml");
INSERT INTO Dosages (RecipeId, IngredientId, Amount, Unit) VALUES (62, 4, 22.5, "ml");
INSERT INTO Dosages (RecipeId, IngredientId, Amount, Unit) VALUES (62, 14, 22.5, "ml");
INSERT INTO Dosages (RecipeId, IngredientId, Amount, Unit) VALUES (62, 84, 22.5, "ml");
INSERT INTO Dosages (RecipeId, IngredientId, Amount, Unit) VALUES (63, 15, 4.5, "cl");
INSERT INTO Dosages (RecipeId, IngredientId, Amount, Unit) VALUES (63, 7, 3, "cl");
INSERT INTO Dosages (RecipeId, IngredientId, Amount, Unit) VALUES (63, 23, 1.5, "cl");
INSERT INTO Dosages (RecipeId, IngredientId, Amount, Unit) VALUES (63, 109, 6, "cl");
INSERT INTO Dosages (RecipeId, IngredientId, Amount, Unit) VALUES (64, 15, 45, "ml");
INSERT INTO Dosages (RecipeId, IngredientId, Amount, Unit) VALUES (64, 105, 45, "ml");
INSERT INTO Dosages (RecipeId, IngredientId, Amount, Unit) VALUES (64, 110, 7.5, "ml");
INSERT INTO Dosages (RecipeId, IngredientId, Amount, Unit) VALUES (65, 15, 60, "ml");
INSERT INTO Dosages (RecipeId, IngredientId, Amount, Unit) VALUES (65, 94, 10, "ml");
INSERT INTO Dosages (RecipeId, IngredientId, Amount, Unit) VALUES (66, 1, 6, "cl");
INSERT INTO Dosages (RecipeId, IngredientId, Amount, Unit) VALUES (66, 4, 2, "cl");
INSERT INTO Dosages (RecipeId, IngredientId, Amount, Unit) VALUES (66, 99, 2, "barspoons ");
INSERT INTO Dosages (RecipeId, IngredientId, Amount, Unit) VALUES (67, 15, 4.5, "cl");
INSERT INTO Dosages (RecipeId, IngredientId, Amount, Unit) VALUES (67, 7, 1.5, "cl");
INSERT INTO Dosages (RecipeId, IngredientId, Amount, Unit) VALUES (67, 111, 1.5, "cl");
INSERT INTO Dosages (RecipeId, IngredientId, Amount, Unit) VALUES (67, 94, 0.5, "cl");
INSERT INTO Dosages (RecipeId, IngredientId, Amount, Unit) VALUES (67, 37, 1, "entire");
INSERT INTO Dosages (RecipeId, IngredientId, Amount, Unit) VALUES (68, 15, 4, "cl");
INSERT INTO Dosages (RecipeId, IngredientId, Amount, Unit) VALUES (68, 95, 1, "cl");
INSERT INTO Dosages (RecipeId, IngredientId, Amount, Unit) VALUES (68, 7, 1, "cl");
INSERT INTO Dosages (RecipeId, IngredientId, Amount, Unit) VALUES (68, 97, 2, "dashes");
INSERT INTO Dosages (RecipeId, IngredientId, Amount, Unit) VALUES (69, 16, 52.5, "ml");
INSERT INTO Dosages (RecipeId, IngredientId, Amount, Unit) VALUES (69, 43, 7.5, "ml");
INSERT INTO Dosages (RecipeId, IngredientId, Amount, Unit) VALUES (69, 112, 1, "Bar");
INSERT INTO Dosages (RecipeId, IngredientId, Amount, Unit) VALUES (69, 7, 15, "ml");
INSERT INTO Dosages (RecipeId, IngredientId, Amount, Unit) VALUES (69, 34, 1, "barspoon");
INSERT INTO Dosages (RecipeId, IngredientId, Amount, Unit) VALUES (69, 68, 2, "dashes");
INSERT INTO Dosages (RecipeId, IngredientId, Amount, Unit) VALUES (70, 28, 45, "ml");
INSERT INTO Dosages (RecipeId, IngredientId, Amount, Unit) VALUES (70, 113, 30, "ml");
INSERT INTO Dosages (RecipeId, IngredientId, Amount, Unit) VALUES (70, 105, 30, "ml");
INSERT INTO Dosages (RecipeId, IngredientId, Amount, Unit) VALUES (71, 1, 3, "cl");
INSERT INTO Dosages (RecipeId, IngredientId, Amount, Unit) VALUES (71, 87, 3, "cl");
INSERT INTO Dosages (RecipeId, IngredientId, Amount, Unit) VALUES (71, 3, 3, "cl");
INSERT INTO Dosages (RecipeId, IngredientId, Amount, Unit) VALUES (71, 7, 2, "cl");
INSERT INTO Dosages (RecipeId, IngredientId, Amount, Unit) VALUES (72, 15, 45, "ml");
INSERT INTO Dosages (RecipeId, IngredientId, Amount, Unit) VALUES (72, 7, 15, "ml");
INSERT INTO Dosages (RecipeId, IngredientId, Amount, Unit) VALUES (72, 84, 15, "ml");
INSERT INTO Dosages (RecipeId, IngredientId, Amount, Unit) VALUES (72, 114, 1, "barspoon");
INSERT INTO Dosages (RecipeId, IngredientId, Amount, Unit) VALUES (73, 15, 3, "cl");
INSERT INTO Dosages (RecipeId, IngredientId, Amount, Unit) VALUES (73, 115, 3, "cl");
INSERT INTO Dosages (RecipeId, IngredientId, Amount, Unit) VALUES (73, 116, 3, "cl");
INSERT INTO Dosages (RecipeId, IngredientId, Amount, Unit) VALUES (74, 106, 3, "cl");
INSERT INTO Dosages (RecipeId, IngredientId, Amount, Unit) VALUES (74, 13, 3, "cl");
INSERT INTO Dosages (RecipeId, IngredientId, Amount, Unit) VALUES (74, 20, 1, "splash");
INSERT INTO Dosages (RecipeId, IngredientId, Amount, Unit) VALUES (75, 87, 30, "ml");
INSERT INTO Dosages (RecipeId, IngredientId, Amount, Unit) VALUES (75, 86, 30, "ml");
INSERT INTO Dosages (RecipeId, IngredientId, Amount, Unit) VALUES (75, 80, 30, "ml");
