name: Build and Push Docker Image to GCP

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - id: 'auth'
        uses: 'google-github-actions/auth@v1'
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v1
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}
     
      - name: Configure Docker
        env:
          REPO_URL: europe-west3-docker.pkg.dev
        run: |
          gcloud auth configure-docker $REPO_URL --quiet 

      - name: (API) Build and Push Docker image 
        env:
          REPO_URL: europe-west3-docker.pkg.dev
          PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
          REPO_NAME: ${{ secrets.GCP_REPO_NAME }}
          IMAGE_NAME: ${{ secrets.GCP_PROJECT_ID }}-api
          TAG: latest
        run: |
          docker build -t $REPO_URL/$PROJECT_ID/$REPO_NAME/$IMAGE_NAME:latest .
          docker push $REPO_URL/$PROJECT_ID/$REPO_NAME/$IMAGE_NAME:latest
        working-directory: api

      - name: (FRONTEND) Build and Push Docker image 
        env:
          REPO_URL: europe-west3-docker.pkg.dev
          API_URL: ${{ secrets.API_URL }}
          PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
          REPO_NAME: ${{ secrets.GCP_REPO_NAME }}
          IMAGE_NAME: ${{ secrets.GCP_PROJECT_ID }}-frontend
          TAG: latest
        run: |
          docker build --build-arg VITE-BARCABINET_API_URL=$API_URL $REPO_URL/$PROJECT_ID/$REPO_NAME/$IMAGE_NAME:latest .
          docker push $REPO_URL/$PROJECT_ID/$REPO_NAME/$IMAGE_NAME:latest
        working-directory: frontend

