name: NodeJS API CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [ 18.x ]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Build and run database image 
      run: |
        docker build -t test-db .
        docker run -d --name mysql-ci-test -e MYSQL_ROOT_PASSWORD=temp -p 3306:3306 -t test-db
      working-directory: db

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}

    - name: Install Dependencies
      run: yarn
      working-directory: api

    - name: Create .env.test file
      run: |
        touch .env.test
        echo JWT_SECRET=TESTING_SECRET >> .env.test
        echo DATABASE_URL=mysql://api_user:secret@localhost:3306/cocktails >> .env.test
        cat .env.test
      working-directory: api

    - name: Run Linter
      run: yarn lint
      working-directory: api

    - name: Run Unit Tests
      run: yarn test 
      working-directory: api

    - name: Run Acceptance Tests
      run: yarn test:accept
      working-directory: api

    - name: Stop containers
      if: always()
      run: docker stop mysql-ci-test
