# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: NodeJS API CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [ 18.x ]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Build and run containers
      run: docker-compose -f "docker-compose.yml" up -d --build

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}

    - name: Install Dependencies
      run: yarn
      working-directory: api

    - name: Run Linter
      run: yarn lint
      working-directory: api

    - name: Run unit tests
      run: yarn unit
      working-directory: api

    - name: Run acceptance tests
      run: yarn accept
      working-directory: api

    - name: Stop containers
      if: always()
      run: docker-compose -f "docker-compose.yml" down
